# Generated by Django 3.1 on 2020-08-12 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_userrequest_requesteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRequest_Status', to='mysite.statusmaster'),
        ),
    ]
