# Generated by Django 3.1 on 2020-08-12 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200812_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
